DROP DATABASE IF EXISTS reviewdb;

CREATE DATABASE reviewdb;

USE reviewdb;

CREATE TABLE Users (
    id int auto_increment,
    username varchar(55) not null,
    avi varchar(255) not null,
    primary key (id)
);

CREATE TABLE Places (
    id int auto_increment,
    placename varchar(255) not null,
    primary key (id)
);

CREATE TABLE Reviews (
    id int auto_increment,
    datestamp varchar(55) not null,
    body varchar(1000) not null,
    cleanliness int not null,
    communication int not null,
    checkin int not null,
    accuracy int not null,
    location int not null,
    value int not null,
    user int not null,
    foreign key (user) references Users (id),
    place int not null,
    foreign key (place) references Places (id),
    primary key (id)
);

INSERT INTO `Users` (`username`,`avi`) VALUES ("Dean Burnett","https://garlic-ly-reviews.s3-us-west-1.amazonaws.com/imgplaceholder.svg");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Dean Lambert","https://garlic-ly-reviews.s3-us-west-1.amazonaws.com/imgplaceholder.svg");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Rhoda Hull","https://garlic-ly-reviews.s3-us-west-1.amazonaws.com/imgplaceholder.svg");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Dieter Potter","https://garlic-ly-reviews.s3-us-west-1.amazonaws.com/imgplaceholder.svg");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Bruce Burks","https://garlic-ly-reviews.s3-us-west-1.amazonaws.com/imgplaceholder.svg");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Jescie Shepard","https://garlic-ly-reviews.s3-us-west-1.amazonaws.com/imgplaceholder.svg");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Desiree Burt","CRS33BQD3HD");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Jordan Moon","KRE17MOD3IZ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Juliet Hughes","BGL40VWM7QR");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Julian Santos","ACI96DFA7FF");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Marvin Delacruz","NWA72OJX9HK");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Georgia Best","FZN51JUY9CW");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Elvis Mcpherson","HQZ48INV1UK");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Dolan Norris","ZKG98SWN6AH");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Micah Cunningham","ODQ37ENG0HN");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Odette Whitehead","CZO40ZIE1FP");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Haviva Morgan","FTR42SDI1AS");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Patrick Cobb","NHI03RXU6CJ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Ivy Hull","DYR48YNW6GU");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Vance Harris","JOR69KSW1NB");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Peter Wiggins","HPG29IWT8KR");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Rowan Chase","SAL75ZKP8CC");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Aurora Flores","BTP82YTL1QK");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Graham Sims","SFW44GVB2YB");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Uriel Kane","IXC29LSR2UT");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Quentin Roberts","XJY26BGS0QV");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Ivan Kennedy","VVS21KJH4CR");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Damian Duffy","KNE71LWJ7JE");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Blake Carlson","VOJ88CRK6OJ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Cody Monroe","QFW41EWQ4OF");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Jeremy Bowen","NGQ17SUE4DB");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Ori Alvarado","HZS11XOK5LM");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Irma Hayes","KXT28CRS6BO");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Kylee Britt","QWG57PCB6WH");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Paul Doyle","VVO24PKK5AX");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Nita Bolton","KNW63EBW1AC");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Devin Obrien","GBV91XPI9CY");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Destiny Jacobs","QFR56BHC6BJ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Kenyon Rosa","CIC94XTM2UJ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Jonas Moore","LWF04SXZ4UO");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Brenda Espinoza","UEY97WLR7GI");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Charissa Ramsey","KZK45RYQ2HH");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Jolene Macias","MDE36IMV7VO");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Asher Shannon","AQV56FJN0OQ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Dominic Hendrix","HVL70EVG4EO");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Dane Oneil","KEB56CGX4QA");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Quail Boyle","JJH34OKO8HG");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Lunea Olsen","IZV63BIT8IZ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Veronica Chavez","GHF17HXH0LH");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Serena Wilson","EXN60RXP1UV");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Cailin Jarvis","XBT43JBS5DA");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Kenneth Maddox","GUO06ZDH3KK");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Owen Parsons","FSJ03SZI8UL");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Risa Moon","RDZ96WRZ7RK");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Veronica Fuentes","CGZ30EVM9MA");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Chaney Stein","ZYX08CVT3KN");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Hedley Key","ZVX34ASY4XO");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Hu Huffman","HLT60BSH3RR");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Dennis Moran","JMR35KDO8SU");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Burke Potter","RHD87YGR0HN");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Ira Reyes","ZNB94MKL1OA");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Shelley Hanson","JED19OES5UX");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Dara Herring","KMR12SNB7FG");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Lars Byrd","TID22NCA2WQ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Bell Mccall","UTY83ACG5PC");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Candace Ramirez","MHN82FIA0IE");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Rhoda Mack","FBS66JJQ1ZA");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Brandon Gill","ERQ33JHK2FH");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Shana Horne","HMY90IJC6XO");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Kato Burton","YGB44NSG9RV");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Ulric Fry","FQM42ISP1SA");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Naida Ellis","DEI20YFX5GR");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Melyssa Wells","UKE06XGA9BN");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Xyla Riddle","EJG50ZZR5GY");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Dolan Cardenas","PLU96HYA1WG");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Cyrus Ray","UPE45TFL0UW");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Jamalia Douglas","JRJ19BHP2YV");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Mark York","VLF26NIG2GE");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Melanie Skinner","DGP35FUF8SS");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Myra Farmer","FEM62LXK9YT");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Adrienne Castaneda","WHR39QCF1TZ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Yoshio Pickett","DZG53GQE8RA");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Rina Dillon","SWP60WGY7JX");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Riley Cole","PKI83CBQ3WA");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Pandora Swanson","VHN07HSA7AI");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Keelie Lott","MLD53PAI8DO");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Kibo Huber","MWA85OWP4AR");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Zephania Sellers","NCF00VPE1FB");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Emery Hardin","UXR95EJR3HO");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Madeline Dean","GNP09OLX3YJ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Elmo Cortez","BJS54EXS8XM");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Nehru Barrera","TJT75ZVT9JC");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Cole Green","CYN23PTY0NA");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Xandra Sharp","YVM79FWB9JO");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Chaim Park","RSX01RDZ4DI");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Delilah Fry","NNG04YGX8KX");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Hamilton Dawson","YNM39OWV3WQ");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Breanna Hall","DVI48LNO0QH");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Maia Perez","QLU93ZQG9RF");
INSERT INTO `Users` (`username`,`avi`) VALUES ("Martha Sweet","JBQ80EME0LH");

INSERT INTO `Places` (`placename`) VALUES ("Oahu Beachfront Apartment");

INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,5,3,5,1,5,"et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere","May 24th, 2020",1,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,1,3,3,3,1,"sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor","August 25th, 2019",2,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,1,5,4,4,4,"fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit,","May 30th, 2020",3,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,1,4,2,5,3,"quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin","September 19th, 2019",4,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,5,1,1,2,2,"magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi","December 13th, 2019",5,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,5,3,2,4,1,"cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum","September 19th, 2019",6,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,4,3,2,1,2,"tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci","February 26th, 2020",7,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,5,3,2,3,1,"vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida","September 29th, 2019",8,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,1,4,1,2,2,"mus. Proin vel arcu eu odio tristique pharetra. Quisque ac","January 7th, 2020",9,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,4,4,1,1,2,"sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est,","May 6th, 2020",10,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,1,3,1,5,1,"consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum.","May 31st, 2020",11,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,2,1,3,2,2,"ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac","June 19th, 2019",12,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,3,2,5,5,1,"In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend","August 18th, 2019",13,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,1,3,2,4,3,"erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac","February 25th, 2020",14,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,2,5,3,5,5,"et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,","July 4th, 2019",15,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,4,2,4,3,3,"a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas","May 11th, 2020",16,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,5,2,3,2,1,"luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam","January 8th, 2020",17,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,3,4,5,5,2,"Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin","December 29th, 2019",18,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,2,4,5,2,2,"gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et,","December 30th, 2019",19,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,1,5,2,3,1,"Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed","March 2nd, 2020",20,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,3,4,5,4,5,"Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem","February 26th, 2020",21,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,1,2,1,3,4,"aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet,","August 8th, 2019",22,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,4,4,1,4,3,"ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi","July 17th, 2019",23,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,5,2,2,5,1,"Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet","June 23rd, 2019",24,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,5,1,5,2,4,"vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis","August 14th, 2019",25,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,4,5,1,2,4,"gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac","March 28th, 2020",26,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,5,5,5,4,5,"Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem","October 30th, 2019",27,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,4,5,3,5,3,"mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget","December 4th, 2019",28,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,3,5,5,3,3,"bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis","September 17th, 2019",29,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,2,5,2,3,1,"Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum","June 19th, 2019",30,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,5,4,2,2,5,"id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus","February 27th, 2020",31,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,5,5,3,5,2,"nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean","August 29th, 2019",32,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,3,3,4,2,2,"iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc","September 7th, 2019",33,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,5,1,1,4,4,"arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel","October 12th, 2019",34,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,2,5,2,5,4,"fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit","January 19th, 2020",35,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,1,5,3,3,1,"Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris","October 30th, 2019",36,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,2,3,2,1,2,"hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at","September 3rd, 2019",37,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,5,5,4,2,1,"vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet","May 11th, 2020",38,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,5,3,4,4,2,"cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut","February 10th, 2020",39,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,4,5,2,1,5,"purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut","September 12th, 2019",40,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,1,5,4,3,2,"Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque","December 26th, 2019",41,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,5,5,2,1,5,"Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus","July 5th, 2019",42,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,3,5,1,5,3,"et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse","February 17th, 2020",43,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,5,4,4,1,1,"Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc","August 21st, 2019",44,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,5,3,1,2,3,"non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis","April 2nd, 2020",45,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,4,1,2,5,3,"Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio","June 15th, 2020",46,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,1,5,1,3,3,"et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas","January 11th, 2020",47,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,1,3,5,2,4,"est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin","March 17th, 2020",48,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,4,2,4,4,5,"ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem","December 26th, 2019",49,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,2,5,5,5,4,"nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et","December 29th, 2019",50,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,1,2,1,4,3,"vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris","October 28th, 2019",51,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,2,1,4,2,3,"magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio","May 1st, 2020",52,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,5,1,5,5,3,"placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris","July 10th, 2019",53,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,5,4,1,1,1,"turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue","February 18th, 2020",54,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,3,2,5,4,5,"eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis","November 7th, 2019",55,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,4,1,4,1,1,"amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi","February 2nd, 2020",56,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,1,2,5,3,1,"vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus,","April 13th, 2020",57,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,1,4,3,3,3,"nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed","August 19th, 2019",58,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,4,1,1,2,3,"venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent","May 4th, 2020",59,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,4,2,5,5,1,"ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin","July 26th, 2019",60,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,1,4,3,1,3,"fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo","June 13th, 2020",61,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,2,2,5,2,1,"tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient","August 3rd, 2019",62,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,4,5,2,2,2,"magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat,","January 19th, 2020",63,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,4,2,1,4,5,"enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper","August 11th, 2019",64,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,1,3,3,1,1,"adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in","September 17th, 2019",65,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,3,2,3,3,2,"scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor.","October 10th, 2019",66,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,4,3,3,3,4,"Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet","April 25th, 2020",67,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,3,3,5,2,5,"natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam.","June 7th, 2020",68,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,4,5,1,3,1,"sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium","July 22nd, 2019",69,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,5,1,5,3,1,"Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel","September 21st, 2019",70,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,1,3,2,3,5,"Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum.","January 12th, 2020",71,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,2,2,2,2,1,"in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac","November 23rd, 2019",72,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,4,2,4,3,5,"sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra.","February 10th, 2020",73,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,1,3,3,3,1,"a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis","January 23rd, 2020",74,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,1,3,4,2,1,"sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est","September 22nd, 2019",75,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,4,5,3,1,1,"mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at,","November 19th, 2019",76,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,1,5,2,2,4,"nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis,","September 12th, 2019",77,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,3,3,3,2,2,"In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat","March 14th, 2020",78,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,4,4,1,4,5,"gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac,","July 16th, 2019",79,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,1,2,4,2,4,"aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras","February 24th, 2020",80,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,3,4,3,1,1,"non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque","December 25th, 2019",81,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,1,1,2,5,2,"vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis","June 9th, 2020",82,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,5,1,3,3,5,"Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales","May 10th, 2020",83,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,2,2,2,2,1,"eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam","October 29th, 2019",84,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,1,4,5,2,3,"amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem,","April 18th, 2020",85,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,2,4,2,1,1,"Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare","December 10th, 2019",86,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (1,4,5,5,5,1,"magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem","May 30th, 2020",87,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,1,2,1,4,3,"tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac","November 5th, 2019",88,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,3,2,4,1,2,"Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla.","September 12th, 2019",89,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,2,1,4,3,3,"volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi","November 12th, 2019",90,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,3,5,4,2,2,"porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc","January 16th, 2020",91,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (3,5,4,5,4,3,"in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta","July 8th, 2019",92,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,2,3,2,3,4,"pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit","February 3rd, 2020",93,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,1,5,1,4,5,"vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris","August 28th, 2019",94,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (4,1,4,2,1,1,"ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque","July 17th, 2019",95,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,3,5,2,1,4,"eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in","July 25th, 2019",96,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (2,2,4,1,5,1,"Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum","January 27th, 2020",97,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,2,2,2,1,4,"lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem","October 13th, 2019",98,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,3,1,2,2,4,"erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras","July 19th, 2019",99,1);
INSERT INTO `Reviews` (`cleanliness`,`communication`,`checkin`,`accuracy`,`location`,`value`,`body`,`datestamp`,`user`,`place`) VALUES (5,2,2,1,2,5,"interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu","April 28th, 2020",100,1);